[theme]
primaryColor = "#FF4B4B"            # Button, highlights
backgroundColor = "#0E1117"         # Main background
secondaryBackgroundColor = "#262730" # Sidebar / cards
textColor = "#FFFFFF"               # Text color
font = "sans serif"
